### PR TITLE
Adds Support for More Emoji Styles & Improves Preferences Menu

### LINKED ISSUE #6: Provide more emoji icon packs for opinionated users
I think a big step would be to offer [twemoji](https://github.com/twitter/twemoji) and [noto-emoji](https://github.com/googlefonts/noto-emoji), as those are the most common emoji packs used. 

We could have a settings menu setting to manage which style of emoji the user prefers, and keep the default on 'apple' (the style of emojis being used now).

### PR DESCRIPTION
**Pull request by MyriaCore**
Delivers and closes #6. Also updates and improves the preferences available to the user.  
Blocks #9. Merge is blocked by review of #9 (see https://github.com/Ulauncher/ulauncher-emoji/pull/8#issuecomment-663125817).

While this MR is being reviewed, users can install [my fork](https://github.com/MyriaCore/ulauncher-emoji) via Ulauncher's plugin install system, since the `emoji-packs` branch has been merged into `master` courtesy of MyriaCore/ulauncher-emoji#1. 

### Known Bug

The skin tone selection doesn't work, and just returns emojis of the default skin tone. This happens because the [unicode.org site](https://unicode.org/emoji/charts/emoji-list.html) that's scraped to update the emoji data in `emoji.sqlite` no longer shows skin tone variants of emojis, or emoji sequences / variations in general. Those can be found at [this](https://unicode.org/emoji/charts/full-emoji-modifiers.html) page. 

This appears to be fixed by a10bc58, but that's on another branch, and therefore isn't available in this PR. It *is* available in the master branch of  [my fork](https://github.com/MyriaCore/ulauncher-emoji), as per https://github.com/MyriaCore/ulauncher-emoji/pull/2.

### New Features / changes

- `EmojiSpider.py` now pulls in emoji icons from [twemoji](https://github.com/twitter/twemoji), [noto-emoji](https://github.com/googlefonts/noto-emoji), and [blobmoji](https://github.com/c1710/blobmoji), as well as the [unicode.org](http://unicode.org/emoji/charts/emoji-list.html) (we'll call icons from unicode.org 'apple' style, since that's what they look most similar to)
- Icons have been updated with `EmojiSpider.py`, which means Emoji v13 is now supported by twemoji and apple emojis, and Emoji v12 is supported by blobmoji and noto-emoji.
- Added **Emoji Style** and **Fallback Emoji Style** options in Preferences Menu for picking emoji style. **Fallback Emoji Style** is useful for when the user prefers an emoji style that runs behind the emoji spec. When an icon cannot be found in the user's preferred style, the icon from the fallback style is used instead. 
- Added **Display System Emoji** option in Preferences Menu. This is a useful 'catch-all' and will just display the emoji to the right of the name inline with the text. This is a remnant from my attempts at #5, but is still a useful option to have. It's turned off by default to prevent confusion. 
- Main Extension Icon changed to be sourced from twemoji. Default emoji style is also now twemoji. Twitter's emojis are probably the most recognizable, being used in popular apps like Discord, Github, Gitlab, etc. 
- Changed how the skin-tone preference is displayed visually. Now shows a :ok_hand: with the proper skin tone next to the name of the skin tone. 
- Updated screenshots in readme to reflect these changes :heart:

### Technical Information

The structure of the `emoji.sqlite` database has been changed to accomplish multiple emoji styles. Here are some screenshots of what the `emoji` and `skin_tone` tables look like now:

image

image

All I've done is removed the `icon` column, and added an `icon` column for each supported emoji style. Changes have been made to all relevant areas of the extension to account for this, but it's technically a breaking change, so I figured I'd include it in this report.  

Another important note is that the `icon_{STYLE}` columns *can be null*. If they're null, it means that the icon for that style could not be retrieved by the scraper. This is checked by the main extension logic to determine if the user's fallback style should be used.

### CODE REVIEW

**Comment by MyriaCore** [comment]
Ignore my musings, they were just working notes as I debugged my implementation. All of these threads should be considered resolved.

**Comment by gornostal** [comment]
Wow! A lot of work has been put into this :+1: 
Thank you for the PR @MyriaCore 

I'll try to find time to review it this week.

**Comment by MyriaCore** [comment]
@gornostal Any updates?

**Comment by MyriaCore** [comment]
I just noticed through a bit of use that I'm experiencing one last bug. If the fallback emoji style doesn't have one of the emojis, but the normal style *does*, then the plugin will fail to get the emoji. 

I'm gonna work on resolving that now.

**Comment by MyriaCore** [comment]
Alright, that should fix it. I basically changed the DB structure such that, if an icon for an emoji style couldn't be retrieved, it's just not inserted into the database. So, then we can check in main.py if the database returned anything useful, and if not, go for the fallback.

**Comment by MyriaCore** [comment]
@gornostal I just wanted to quickly point out that I've been waiting for this to be merged before starting work on #7, because I'd likely want to use logic from this branch. I could just fork it now and start working on it anyways, but I don't know what your views on proper process are for this.

Do you recommend I keep waiting, or is it fine with you if I make a new branch in my fork to start implementing #7?

**Comment by MyriaCore** [comment]
@gornostal just found another bug in my daily use! It's mentioned in https://github.com/Ulauncher/ulauncher-emoji/pull/9#issuecomment-662730133 and appears like it might be fixed by a10bc58 in #9, which makes things a bit tricky (I probably shouldn't have patched it there when I did). I'm currently running the EmojiSpider, so we'll see if this edit fixed things. 

To fix the weird merging issues, we'll probably want to have the review of #9 block this PR's merge. That way, you can just review both when you have time, and we'll merge them both in at the same time so we can bring the relevant commits in #9 to fix this issue.

**Comment by MyriaCore** [comment]
@gornostal Bump? I'm gonna go to school soon so I won't be able to keep tabs on this. Hope you get some time to review soon!

Remember, review this first, then do #9!

**Pull request merged**
